SELECT DISTINCT
    CAST(syd_AD.FECHA_CREACION AS DATE) AS FECHA_ALTA,
    DOC.STATUS,
    CAST(SYD.DOC_EXT AS VARCHAR(50)) AS DOC_EXT,
    p_aux.PRODUCTO_ID,
    ISNULL(p_aux.qty_proc, 0) AS Cantidad_Procesada,
    ISNULL(p_aux.qty_conf, 0) AS Cantidad_Confirmada,
    (SELECT MIN(CAST(V1.NRO_CONTENEDORA_EMPAQUE AS VARCHAR(50)))
       FROM VIEW_TIEMPO_EMPAQUETADO V1 (NOLOCK)
      WHERE V1.PEDIDO = SYD.DOC_EXT
        AND V1.CLIENTE_ID = SYD.CLIENTE_ID
        AND V1.NRO_CONTENEDORA_EMPAQUE IS NOT NULL) AS NRO_CONTENEDORA_EMPAQUE,
    (SELECT COUNT(DISTINCT V2.NRO_CONTENEDORA_EMPAQUE)
       FROM VIEW_TIEMPO_EMPAQUETADO V2 (NOLOCK)
      WHERE V2.PEDIDO = SYD.DOC_EXT
        AND V2.CLIENTE_ID = SYD.CLIENTE_ID
        AND V2.NRO_CONTENEDORA_EMPAQUE IS NOT NULL) AS CAJAS,
    (SELECT STUFF((SELECT ' | ' + CAST(V3.NRO_CONTENEDORA_EMPAQUE AS VARCHAR(50))
                     FROM VIEW_TIEMPO_EMPAQUETADO V3 (NOLOCK)
                    WHERE V3.PEDIDO = SYD.DOC_EXT
                      AND V3.CLIENTE_ID = SYD.CLIENTE_ID
                      AND V3.NRO_CONTENEDORA_EMPAQUE IS NOT NULL
                    GROUP BY CAST(V3.NRO_CONTENEDORA_EMPAQUE AS VARCHAR(50))
                    ORDER BY CAST(V3.NRO_CONTENEDORA_EMPAQUE AS VARCHAR(50))
                      FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 3, '')) AS CONTENEDORAS
FROM SYS_INT_DOCUMENTO syd (NOLOCK)
LEFT JOIN SYS_INT_DET_DOCUMENTO syded (NOLOCK)
    ON (syd.doc_ext = syded.doc_ext AND syd.cliente_id = syded.cliente_id)
LEFT JOIN SYS_INT_DOCUMENTO_ADICIONAL syd_ad (NOLOCK)
    ON (syd.doc_ext = syd_ad.doc_ext AND syd.cliente_id = syd_ad.cliente_id)
LEFT JOIN TIPO_COMPROBANTE tc (NOLOCK)
    ON (tc.TIPO_COMPROBANTE_ID = syd.TIPO_DOCUMENTO_ID)
LEFT JOIN DOCUMENTO doc (NOLOCK)
    ON (doc.DOCUMENTO_ID = syded.DOCUMENTO_ID)
LEFT JOIN (
    SELECT
        p.DOCUMENTO_ID,
        p.PRODUCTO_ID,
        SUM(p.CANTIDAD) AS qty_proc,
        SUM(ISNULL(p.CANT_CONFIRMADA, 0)) AS qty_conf
    FROM picking p (NOLOCK)
    GROUP BY
        p.DOCUMENTO_ID,
        p.PRODUCTO_ID
) p_aux ON (p_aux.DOCUMENTO_ID = doc.DOCUMENTO_ID)
WHERE (UPPER(tc.TIPO_OPERACION_ID) = 'EGR' OR UPPER(doc.TIPO_OPERACION_ID) = 'EGR')
  AND SYD.cliente_id IN ('HYCITE2')
  AND syd_AD.FECHA_CREACION >= DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
