SELECT
    MIN(d.FECHA_ALTA) AS FECHA_ALTA,
    MAX(d.STATUS) AS STATUS,
    d.DOC_EXT AS DOC_EXT,
    pk.PRODUCTO_ID AS PRODUCTO_ID,
    ISNULL(SUM(pk.CANT_PROC), 0) AS Cantidad_Procesada,
    ISNULL(SUM(pk.CANT_CONF), 0) AS Cantidad_Confirmada,
    MIN(e.NRO_CONTENEDORA_EMPAQUE) AS NRO_CONTENEDORA_EMPAQUE
FROM (
    SELECT DISTINCT
        c.CLIENTE_ID,
        c.DOC_EXT,
        c.FECHA_ALTA,
        doc.DOCUMENTO_ID,
        doc.STATUS
    FROM (
        SELECT
            syd.CLIENTE_ID,
            CAST(syd.DOC_EXT AS VARCHAR(50)) AS DOC_EXT,
            syd.TIPO_DOCUMENTO_ID,
            CAST(MIN(syd_ad.FECHA_CREACION) AS DATE) AS FECHA_ALTA
        FROM SYS_INT_DOCUMENTO syd (NOLOCK)
        INNER JOIN SYS_INT_DOCUMENTO_ADICIONAL syd_ad (NOLOCK)
                ON syd_ad.DOC_EXT = syd.DOC_EXT
               AND syd_ad.CLIENTE_ID = syd.CLIENTE_ID
        WHERE syd.CLIENTE_ID IN ('HYCITE2')
          AND syd_ad.FECHA_CREACION >= DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
        GROUP BY
            syd.CLIENTE_ID,
            CAST(syd.DOC_EXT AS VARCHAR(50)),
            syd.TIPO_DOCUMENTO_ID
    ) c
    INNER JOIN SYS_INT_DET_DOCUMENTO sdd (NOLOCK)
            ON sdd.DOC_EXT = c.DOC_EXT
           AND sdd.CLIENTE_ID = c.CLIENTE_ID
    INNER JOIN DOCUMENTO doc (NOLOCK)
            ON doc.DOCUMENTO_ID = sdd.DOCUMENTO_ID
    LEFT JOIN TIPO_COMPROBANTE tc (NOLOCK)
           ON tc.TIPO_COMPROBANTE_ID = c.TIPO_DOCUMENTO_ID
    WHERE UPPER(ISNULL(tc.TIPO_OPERACION_ID, '')) = 'EGR'
       OR UPPER(ISNULL(doc.TIPO_OPERACION_ID, '')) = 'EGR'
) d
LEFT JOIN (
    SELECT
        p.DOCUMENTO_ID,
        p.PRODUCTO_ID,
        SUM(p.CANTIDAD) AS CANT_PROC,
        SUM(ISNULL(p.CANT_CONFIRMADA, 0)) AS CANT_CONF
    FROM PICKING p (NOLOCK)
    GROUP BY
        p.DOCUMENTO_ID,
        p.PRODUCTO_ID
) pk
       ON pk.DOCUMENTO_ID = d.DOCUMENTO_ID
LEFT JOIN (
    SELECT
        vte.CLIENTE_ID,
        CAST(vte.PEDIDO AS VARCHAR(50)) AS PEDIDO,
        MIN(CAST(vte.NRO_CONTENEDORA_EMPAQUE AS VARCHAR(50))) AS NRO_CONTENEDORA_EMPAQUE
    FROM VIEW_TIEMPO_EMPAQUETADO vte (NOLOCK)
    WHERE vte.NRO_CONTENEDORA_EMPAQUE IS NOT NULL
    GROUP BY
        vte.CLIENTE_ID,
        CAST(vte.PEDIDO AS VARCHAR(50))
) e
       ON e.PEDIDO = d.DOC_EXT
      AND e.CLIENTE_ID = d.CLIENTE_ID
GROUP BY
    d.DOC_EXT,
    pk.PRODUCTO_ID
