section Section1;

shared EMPAQUETADO = let
    Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/<ID_PUBLICADO_OCULTO>/pub?output=csv"),[Delimiter=",", Columns=26, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"FECHA", type date}, {"# ORDEN", Int64.Type}, {"# BULTOS", Int64.Type}, {"TIIPO CAJA", type text}, {"# CONTENEDORA", Int64.Type}, {"VOLUMEN M3", Int64.Type}, {"", type text}, {"MES", Int64.Type}, {"AÑO", Int64.Type}, {"_1", type text}, {"TIPO CAJA", type text}, {"Largo", Int64.Type}, {"Ancho", Int64.Type}, {"Alto", Int64.Type}, {"VOLUMEN", Int64.Type}, {"PESO", Int64.Type}, {"_2", type text}, {"_3", type text}, {"_4", type text}, {"_5", type text}, {"_6", type text}, {"_7", type text}, {"_8", type text}, {"_9", type text}, {"_10", type text}, {"_11", type text}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"# BULTOS", "VOLUMEN M3", "", "MES", "AÑO", "_1", "TIPO CAJA", "Largo", "Ancho", "Alto", "VOLUMEN", "PESO", "_2", "_3", "_4", "_5", "_6", "_7", "_8", "_9", "_10", "_11"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas quitadas",{{"# ORDEN", type text}}),
    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado1", each Date.IsInCurrentDay([FECHA])),
    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [#"# ORDEN"] <> null and [#"# ORDEN"] <> "")
in
    #"Filas filtradas1";

shared Estado = let
    Origen = Odbc.Query("dsn=DEPOTUIO", "SELECT DISTINCT#(lf)    CAST(syd_AD.FECHA_CREACION AS DATE) AS FECHA_ALTA, #(lf)    DOC.STATUS,#(lf)    CAST(SYD.DOC_EXT AS VARCHAR(50)) AS DOC_EXT,#(lf)    p_aux.PRODUCTO_ID,#(lf)    ISNULL(p_aux.qty_proc, 0) AS Cantidad_Procesada,#(lf)    ISNULL(p_aux.qty_conf, 0) AS Cantidad_Confirmada,#(lf)    CAST(VTE.NRO_CONTENEDORA_EMPAQUE AS VARCHAR(50)) AS NRO_CONTENEDORA_EMPAQUE#(lf)FROM SYS_INT_DOCUMENTO syd (NOLOCK)#(lf)LEFT JOIN CLIENTE CL (NOLOCK) #(lf)    ON CL.CLIENTE_ID = SYD.CLIENTE_ID#(lf)LEFT JOIN SYS_INT_DET_DOCUMENTO syded (NOLOCK) #(lf)    ON (syd.doc_ext = syded.doc_ext AND syd.cliente_id = syded.cliente_id)#(lf)LEFT JOIN SYS_INT_DOCUMENTO_ADICIONAL syd_ad (NOLOCK) #(lf)    ON (syd.doc_ext = syd_ad.doc_ext AND syd.cliente_id = syd_ad.cliente_id)#(lf)LEFT JOIN TIPO_COMPROBANTE tc (NOLOCK) #(lf)    ON (tc.TIPO_COMPROBANTE_ID = syd.TIPO_DOCUMENTO_ID)#(lf)LEFT JOIN SUCURSAL SUC (NOLOCK) #(lf)    ON (suc.CLIENTE_ID = syd.CLIENTE_ID AND SUC.SUCURSAL_ID = SYD.AGENTE_ID)#(lf)LEFT JOIN VIEW_TIEMPO_EMPAQUETADO VTE (NOLOCK) #(lf)    ON VTE.PEDIDO = SYD.DOC_EXT AND VTE.CLIENTE_ID = syd.CLIENTE_ID#(lf)LEFT JOIN DOCUMENTO doc (NOLOCK) #(lf)    ON (doc.DOCUMENTO_ID = syded.DOCUMENTO_ID)#(lf)LEFT JOIN (#(lf)    SELECT #(lf)        p.DOCUMENTO_ID,#(lf)        p.PICKING_ID,#(lf)        p.PRODUCTO_ID,#(lf)        p.DESCRIPCION,#(lf)        p.CANTIDAD AS CANTIDAD_SOLICITADA,#(lf)        ISNULL(p.CANT_CONFIRMADA, 0) AS CANT_CONFIRMADA,#(lf)        p.POSICION_COD,#(lf)        p.PROP1,#(lf)        P.NRO_LOTE,#(lf)        P.NRO_PARTIDA,#(lf)        P.NRO_SERIE,#(lf)        SUM(p.CANTIDAD) AS qty_proc,#(lf)        SUM(p.CANT_CONFIRMADA) AS qty_conf,#(lf)        MAX(CASE WHEN p.fin_picking = 2 THEN P.FECHA_FIN ELSE NULL END) AS fecha_fin_picking,#(lf)        MIN(p.FECHA_UCEMPAQUETADO) AS fecha_min_empaq,#(lf)        MAX(p.FECHA_UCEMPAQUETADO) AS fecha_max_empaq,#(lf)        SUM(CASE WHEN p.nro_ucempaquetado IS NULL THEN P.CANT_CONFIRMADA ELSE 0 END) AS qty_pendiente_empaq,#(lf)        SUM(CASE WHEN p.nro_ucempaquetado IS NOT NULL THEN P.CANT_CONFIRMADA ELSE 0 END) AS qty_ya_empaq#(lf)    FROM picking p (NOLOCK)#(lf)    GROUP BY #(lf)        p.DOCUMENTO_ID,#(lf)        p.PRODUCTO_ID,#(lf)        p.DESCRIPCION,#(lf)        p.CANTIDAD,#(lf)        p.CANT_CONFIRMADA,#(lf)        p.POSICION_COD,#(lf)        p.PROP1,#(lf)        P.NRO_LOTE,#(lf)        P.NRO_PARTIDA,#(lf)        P.NRO_SERIE,#(lf)        P.POSICION_COD,#(lf)        p.PICKING_ID#(lf)) p_aux ON (p_aux.DOCUMENTO_ID = doc.DOCUMENTO_ID)#(lf)WHERE (UPPER(tc.TIPO_OPERACION_ID) = 'EGR' OR UPPER(doc.TIPO_OPERACION_ID) = 'EGR')#(lf)  AND SYD.cliente_id IN ('HYCITE2')#(lf)#(lf)  -- 🔄 FILTRO DINÁMICO: Desde ayer a las 00:00:00 en adelante#(lf)  AND syd_AD.FECHA_CREACION >= DATEADD(DAY, -1, CAST(GETDATE() AS DATE));"),
    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"FECHA_ALTA", type date}})
in
    #"Tipo cambiado";

shared #"ITEMS API" = let
    Origen = Odbc.Query("dsn=DEPOTUIO", "SELECT #(lf)    CLIENTE_ID,#(lf)    DOC_EXT,#(lf)    ESTADO_GT,#(lf)    FECHA_ESTADO_GT,#(lf)    NRO_LINEA,#(lf)    PRODUCTO_ID,#(lf)    CANTIDAD_SOLICITADA,#(lf)    UNIDAD_ID,#(lf)    DOCUMENTO_ID#(lf)FROM SYS_INT_DET_DOCUMENTO WITH (NOLOCK)#(lf)WHERE CLIENTE_ID = 'HYCITE2'#(lf)  -- 🔄 Filtra automáticamente todo lo generado el día de HOY#(lf)  AND FECHA_ESTADO_GT >= CAST(GETDATE() AS DATE)#(lf)  AND FECHA_ESTADO_GT <  CAST(DATEADD(DAY, 1, GETDATE()) AS DATE)#(lf)ORDER BY FECHA_ESTADO_GT DESC, DOC_EXT, NRO_LINEA;")
in
    Origen;
